os:
  - linux
language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install nose
before_script:
- nohup python app.py &
script:
- python test.py
branches:
  only:
    - master
